package user_interface.custom_game_file_management;

import use_cases.custom_game_inner_file_management.CustomGameFileManagerInterface;

public class CustomGameFileManager implements CustomGameFileManagerInterface {
}
